"""updated client model

Revision ID: 1a143d3f8d40
Revises: 35594d4e2e1d
Create Date: 2021-07-14 15:22:36.227991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a143d3f8d40'
down_revision = '35594d4e2e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('password_hash', sa.String(length=150), nullable=False))
    op.add_column('petshops', sa.Column('password_hash', sa.String(length=150), nullable=False))
    op.add_column('petshops', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_column('petshops', 'id_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petshops', sa.Column('id_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('petshops', 'is_admin')
    op.drop_column('petshops', 'password_hash')
    op.drop_column('clients', 'password_hash')
    # ### end Alembic commands ###
