"""deleting cascade order

Revision ID: ae76e8a75e23
Revises: 
Create Date: 2021-07-16 20:47:06.404477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae76e8a75e23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_pet_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'pets', ['pet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_pet_id_fkey', 'orders', 'pets', ['pet_id'], ['id'])
    # ### end Alembic commands ###
