"""added cascade delete on pet model

Revision ID: b5cbdf53e2f2
Revises: 
Create Date: 2021-07-17 06:30:54.579464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5cbdf53e2f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'finished_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('pets_client_id_fkey', 'pets', type_='foreignkey')
    op.create_foreign_key(None, 'pets', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.create_foreign_key('pets_client_id_fkey', 'pets', 'clients', ['client_id'], ['id'])
    op.alter_column('orders', 'finished_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
