"""added cascade delete on order_service model

Revision ID: df16c40825da
Revises: ede115299a92
Create Date: 2021-07-17 06:47:41.856098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df16c40825da'
down_revision = 'ede115299a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_services_services_id_fkey', 'order_services', type_='foreignkey')
    op.drop_constraint('order_services_order_id_fkey', 'order_services', type_='foreignkey')
    op.create_foreign_key(None, 'order_services', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_services', 'services', ['services_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_services', type_='foreignkey')
    op.drop_constraint(None, 'order_services', type_='foreignkey')
    op.create_foreign_key('order_services_order_id_fkey', 'order_services', 'orders', ['order_id'], ['id'])
    op.create_foreign_key('order_services_services_id_fkey', 'order_services', 'services', ['services_id'], ['id'])
    # ### end Alembic commands ###
