"""added cascade delete on address and order model

Revision ID: ede115299a92
Revises: b5cbdf53e2f2
Create Date: 2021-07-17 06:45:27.534169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede115299a92'
down_revision = 'b5cbdf53e2f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('addresses_client_id_fkey', 'addresses', type_='foreignkey')
    op.create_foreign_key(None, 'addresses', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('orders_pet_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'pets', ['pet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_pet_id_fkey', 'orders', 'pets', ['pet_id'], ['id'])
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.create_foreign_key('addresses_client_id_fkey', 'addresses', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###
