"""changed finished_at field

Revision ID: fa6ffd8da0f7
Revises: b14af8e0584e
Create Date: 2021-07-15 19:18:23.675282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa6ffd8da0f7'
down_revision = 'b14af8e0584e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'finished_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('petshops', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_column('petshops', 'id_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petshops', sa.Column('id_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('petshops', 'is_admin')
    op.alter_column('orders', 'finished_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
